### ISSUE TITLE
When compiling and debugging, Registered classes becomes locked.

### ISSUE THREAD

**Issue by vamidi** [RuntimeCompiledCPlusPlus/RuntimeCompiledCPlusPlus#98] opened 2018-08-19 22:32 UTC
When I am trying to debug my code or even re-compile my registered objects, they become locked of temporary deleted? When I go to the folder where they are located I get a message as well that I can't enter the folder. When I restart visual studio the files become available again. Is there a setting I need to set because when I also want to compile again the compiler can not find the files either anymore.

**Comment by dougbinks** [comment] 2018-08-20 10:04
I don't think I've seen this, but I'm not exactly certain I understand what your describing.

What do you mean by 'locked' or temporarily deleted? Do you mean that the source files for your code are locked (cannot be written to) or have disappeared from your drive or visual studio?

During compilation of the source files I expect the VS compiler will indeed lock them, but this should only last a second or so during compilation.

If you could explain in more detail what you are seeing that would be helpful.

**Comment by vamidi** [comment] 2018-08-20 12:27
Yes, it is hard to explain sorry. So the steps that I do are 1. I compile the game, run the game and adjust a file and start to re-compile again, but during compiling everything, I also debug my game to do some testing etc just to see if everything is working fine. when I am done debugging I return to Visual Studio and it says my file is missing. [image](https://puu.sh/BhkZv/18c65c261e.PNG). when I go to my file explorer I don't it and if I refresh it becomes visible again.

**Comment by dougbinks** [comment] 2018-08-20 14:01
I'm trying to repeat this but can't so far, which may be because I have an SSD so the file is read quickly. it shouldn't disappear though, as all that happens is it's being compiled (RCC++ doesn't modify or move source files).

As mentioned debugging during compilation might be an issue, but should be fine after the compilation has stopped. Does this work fine after compilation has stopped?

**Comment by dougbinks** [comment] 2018-08-20 14:43
I still can't get a reproduction of this.

Can you tell me what OS version you are running (Windows 10 etc.), what Visual Studio version and what the file sytem type is (FAT32, NTFS etc.) and what the disk type is (SSD, HDD, network drive etc.)?

**Comment by vamidi** [comment] 2018-08-20 17:28
Currently no problem suddenly. I am running bootcamp windows 10.  Visual studio community 2017 on a SSD (NTFS) drive which has a virtual network drive created in Windows. Maybe I will record it when it happens again. Super for trying to reproduce it

**Comment by vamidi** [comment] 2018-08-25 11:40
Hi @dougbinks I have this problem not so often anymore, maybe it is because I have a virtual drive and that is causing some problems. I can still work though so I think it would be best just to close it for now. Thanks for the help!

**Comment by dougbinks** [comment] 2018-08-25 13:02
Thanks for the further information @vamidi - I'll close the issue but if you see it again let me know and I'll try to work out a reproduction with the same setup.

**Closed by dougbinks** 2018-08-25 13:02 UTC
Labels: Windows, bug
